Configuraciones_Screen As screen:
    BackgroundImage: =FondoAzulClasico
    ImagePosition: =ImagePosition.Stretch

    cms_img_logo_1 As image:
        Image: =logo5
        PaddingBottom: =3
        PaddingLeft: =3
        PaddingRight: =3
        PaddingTop: =3
        Width: =200
        X: =6
        ZIndex: =1

    cms_lbl_titulo_1 As label:
        Align: =Align.Center
        Color: =RGBA(255, 255, 255, 1)
        Font: =Font.Lato
        FontWeight: =FontWeight.Bold
        Height: =60
        Size: =26
        Text: ="Configuraciones"
        Width: =1366
        ZIndex: =2

    cms_img_geografia_1 As image:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        Fill: =RGBA(255, 255, 255, 1)
        Height: =140
        Image: =catalogos2
        PaddingBottom: =20
        PaddingLeft: =10
        PaddingRight: =10
        PaddingTop: =20
        Visible: =vsbBtn
        Width: =170
        X: =357
        Y: =220
        ZIndex: =3

    cms_btn_geografia_1 As button:
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(0, 0, 0, 0)
        DisabledFill: =RGBA(0, 0, 0, 0)
        Fill: =Color.Transparent
        Height: =140
        HoverFill: =Color.Transparent
        OnSelect: =Navigate(Usuarios_Screen,ScreenTransition.CoverRight)
        PressedFill: =Color.Transparent
        Text: =""
        Visible: =vsbBtn
        Width: =170
        X: =357
        Y: =220
        ZIndex: =4

    cms_lbl_geografia_1 As label:
        Align: =Align.Center
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        Fill: =RGBA(255, 255, 255, 1)
        Font: =Font.Lato
        FontWeight: =FontWeight.Semibold
        Height: =36
        Text: ="Usuarios"
        Visible: =vsbBtn
        Width: =170
        X: =357
        Y: =360
        ZIndex: =5

    cms_img_productos_1 As image:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        Fill: =RGBA(255, 255, 255, 1)
        Height: =140
        Image: =catalogos2
        PaddingBottom: =20
        PaddingLeft: =10
        PaddingRight: =10
        PaddingTop: =20
        Visible: =vsbBtn
        Width: =170
        X: =599
        Y: =220
        ZIndex: =6

    cms_btn_productos_1 As button:
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(0, 0, 0, 0)
        DisabledFill: =RGBA(0, 0, 0, 0)
        Fill: =Color.Transparent
        Height: =140
        HoverFill: =Color.Transparent
        OnSelect: =Navigate(Matematica_Screen,ScreenTransition.Fade)
        PressedFill: =Color.Transparent
        Text: =""
        Visible: =vsbBtn
        Width: =170
        X: =599
        Y: =220
        ZIndex: =7

    cms_lbl_productos_1 As label:
        Align: =Align.Center
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        Fill: =RGBA(255, 255, 255, 1)
        Font: =Font.Lato
        FontWeight: =FontWeight.Semibold
        Height: =36
        OnSelect: =Navigate(Matematica_Screen,ScreenTransition.Fade)
        Text: ="Matemática"
        Visible: =vsbBtn
        Width: =170
        X: =599
        Y: =360
        ZIndex: =8

    cms_img_crossReference_1 As image:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        Fill: =RGBA(255, 255, 255, 1)
        Height: =140
        Image: =catalogos2
        PaddingBottom: =20
        PaddingLeft: =10
        PaddingRight: =10
        PaddingTop: =20
        Visible: =vsbBtn
        Width: =170
        X: =357
        Y: =438
        ZIndex: =9

    cms_btn_crossReference_1 As button:
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(0, 0, 0, 0)
        DisabledFill: =RGBA(0, 0, 0, 0)
        Fill: =Color.Transparent
        Height: =140
        HoverFill: =Color.Transparent
        PressedFill: =Color.Transparent
        Text: =""
        Visible: =vsbBtn
        Width: =170
        X: =357
        Y: =438
        ZIndex: =10

    cms_lbl_crossReference_1 As label:
        Align: =Align.Center
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        Fill: =RGBA(255, 255, 255, 1)
        Font: =Font.Lato
        FontWeight: =FontWeight.Semibold
        Height: =36
        Text: ="Impuestos"
        Visible: =vsbBtn
        Width: =170
        X: =357
        Y: =578
        ZIndex: =11

    cms_img_peridosMes_1 As image:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        Fill: =RGBA(255, 255, 255, 1)
        Height: =140
        Image: =catalogos2
        PaddingBottom: =20
        PaddingLeft: =10
        PaddingRight: =10
        PaddingTop: =20
        Visible: =vsbBtn
        Width: =170
        X: =599
        Y: =438
        ZIndex: =12

    cms_btn_periodosMes_1 As button:
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(0, 0, 0, 0)
        DisabledFill: =RGBA(0, 0, 0, 0)
        Fill: =Color.Transparent
        Height: =140
        HoverFill: =Color.Transparent
        PressedFill: =Color.Transparent
        Text: =""
        Visible: =vsbBtn
        Width: =170
        X: =599
        Y: =438
        ZIndex: =13

    cms_lbl_periodosMes_1 As label:
        Align: =Align.Center
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        Fill: =RGBA(255, 255, 255, 1)
        Font: =Font.Lato
        FontWeight: =FontWeight.Semibold
        Height: =36
        Text: ="Tasa de Cambio"
        Visible: =vsbBtn
        Width: =170
        X: =599
        Y: =578
        ZIndex: =14

    cms_img_productos_2 As image:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        Fill: =RGBA(255, 255, 255, 1)
        Height: =140
        Image: =catalogos2
        PaddingBottom: =20
        PaddingLeft: =10
        PaddingRight: =10
        PaddingTop: =20
        Visible: =vsbBtn
        Width: =170
        X: =839
        Y: =220
        ZIndex: =15

    cms_btn_productos_2 As button:
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(0, 0, 0, 0)
        DisabledFill: =RGBA(0, 0, 0, 0)
        Fill: =Color.Transparent
        Height: =140
        HoverFill: =Color.Transparent
        OnSelect: =Navigate(OtrasConfiguraciones_Screen,ScreenTransition.Fade)
        PressedFill: =Color.Transparent
        Text: =""
        Visible: =vsbBtn
        Width: =170
        X: =839
        Y: =220
        ZIndex: =16

    cms_lbl_productos_2 As label:
        Align: =Align.Center
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        Fill: =RGBA(255, 255, 255, 1)
        Font: =Font.Lato
        FontWeight: =FontWeight.Semibold
        Height: =36
        Size: =12
        Text: ="Otras Configuraciones"
        Visible: =vsbBtn
        Width: =170
        X: =839
        Y: =360
        ZIndex: =17

    cms_img_peridosMes_2 As image:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        Fill: =RGBA(255, 255, 255, 1)
        Height: =140
        Image: =catalogos2
        PaddingBottom: =20
        PaddingLeft: =10
        PaddingRight: =10
        PaddingTop: =20
        Visible: =vsbBtn
        Width: =170
        X: =839
        Y: =438
        ZIndex: =18

    cms_btn_periodosMes_2 As button:
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(0, 0, 0, 0)
        DisabledFill: =RGBA(0, 0, 0, 0)
        Fill: =Color.Transparent
        Height: =140
        HoverFill: =Color.Transparent
        PressedFill: =Color.Transparent
        Text: =""
        Visible: =vsbBtn
        Width: =170
        X: =839
        Y: =438
        ZIndex: =19

    cms_lbl_periodosMes_2 As label:
        Align: =Align.Center
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        Fill: =RGBA(255, 255, 255, 1)
        Font: =Font.Lato
        FontWeight: =FontWeight.Semibold
        Height: =36
        Size: =12
        Text: ="New whole sales proce (anual)"
        Visible: =vsbBtn
        Width: =170
        X: =839
        Y: =578
        ZIndex: =20

    ps_img_backP_1 As image:
        Height: =47
        Image: =back
        PaddingBottom: =3
        PaddingTop: =3
        Width: =58
        X: =46
        Y: =715
        ZIndex: =21

    ps_btn_backP_1 As button:
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(0, 0, 0, 0)
        DisabledFill: =RGBA(0, 0, 0, 0)
        Fill: =Color.Transparent
        Height: =47
        HoverFill: =Color.Transparent
        OnSelect: =Navigate(MenuPrincipal_Screen,ScreenTransition.CoverRight)
        PressedFill: =Color.Transparent
        Text: =""
        Width: =58
        X: =46
        Y: =715
        ZIndex: =22

