LogConfiguraciones_Screen As screen:
    BackgroundImage: =FondoAzulClasico
    ImagePosition: =ImagePosition.Stretch

    cms_img_logo_8 As image:
        Image: =logo5
        PaddingBottom: =3
        PaddingLeft: =3
        PaddingRight: =3
        PaddingTop: =3
        Width: =200
        X: =6
        ZIndex: =1

    cms_lbl_titulo_8 As label:
        Align: =Align.Center
        Color: =RGBA(255, 255, 255, 1)
        Font: =Font.Lato
        FontWeight: =FontWeight.Bold
        Height: =60
        Size: =26
        Text: ="Log Configuraciones"
        Width: =1366
        ZIndex: =2

    cms_img_geografia_8 As image:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        Fill: =RGBA(255, 255, 255, 1)
        Height: =140
        Image: =catalogos2
        PaddingBottom: =20
        PaddingLeft: =10
        PaddingRight: =10
        PaddingTop: =20
        Visible: =vsbBtn
        Width: =170
        X: =160
        Y: =280
        ZIndex: =3

    cms_btn_geografia_7 As button:
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(0, 0, 0, 0)
        DisabledFill: =RGBA(0, 0, 0, 0)
        Fill: =Color.Transparent
        Height: =140
        HoverFill: =Color.Transparent
        PressedFill: =Color.Transparent
        Text: =""
        Visible: =vsbBtn
        Width: =170
        X: =160
        Y: =280
        ZIndex: =4

    cms_lbl_geografia_7 As label:
        Align: =Align.Center
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        Fill: =RGBA(255, 255, 255, 1)
        Font: =Font.Lato
        FontWeight: =FontWeight.Semibold
        Height: =36
        Text: ="Usuarios"
        Visible: =vsbBtn
        Width: =170
        X: =160
        Y: =420
        ZIndex: =5

    cms_img_productos_10 As image:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        Fill: =RGBA(255, 255, 255, 1)
        Height: =140
        Image: =catalogos2
        PaddingBottom: =20
        PaddingLeft: =10
        PaddingRight: =10
        PaddingTop: =20
        Visible: =vsbBtn
        Width: =170
        X: =828
        Y: =280
        ZIndex: =6

    cms_btn_productos_8 As button:
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(0, 0, 0, 0)
        DisabledFill: =RGBA(0, 0, 0, 0)
        Fill: =Color.Transparent
        Height: =140
        HoverFill: =Color.Transparent
        PressedFill: =Color.Transparent
        Text: =""
        Visible: =vsbBtn
        Width: =170
        X: =828
        Y: =280
        ZIndex: =7

    cms_lbl_productos_8 As label:
        Align: =Align.Center
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        Fill: =RGBA(255, 255, 255, 1)
        Font: =Font.Lato
        FontWeight: =FontWeight.Semibold
        Height: =36
        OnSelect: =Navigate(Matematica_Screen,ScreenTransition.Fade)
        Text: ="Matemática"
        Visible: =vsbBtn
        Width: =170
        X: =828
        Y: =420
        ZIndex: =8

    cms_img_crossReference_2 As image:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        Fill: =RGBA(255, 255, 255, 1)
        Height: =140
        Image: =catalogos2
        PaddingBottom: =20
        PaddingLeft: =10
        PaddingRight: =10
        PaddingTop: =20
        Visible: =vsbBtn
        Width: =170
        X: =387
        Y: =280
        ZIndex: =9

    cms_btn_crossReference_2 As button:
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(0, 0, 0, 0)
        DisabledFill: =RGBA(0, 0, 0, 0)
        Fill: =Color.Transparent
        Height: =140
        HoverFill: =Color.Transparent
        PressedFill: =Color.Transparent
        Text: =""
        Visible: =vsbBtn
        Width: =170
        X: =387
        Y: =280
        ZIndex: =10

    cms_lbl_crossReference_2 As label:
        Align: =Align.Center
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        Fill: =RGBA(255, 255, 255, 1)
        Font: =Font.Lato
        FontWeight: =FontWeight.Semibold
        Height: =36
        Text: ="Impuestos"
        Visible: =vsbBtn
        Width: =170
        X: =387
        Y: =420
        ZIndex: =11

    cms_img_peridosMes_3 As image:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        Fill: =RGBA(255, 255, 255, 1)
        Height: =140
        Image: =catalogos2
        PaddingBottom: =20
        PaddingLeft: =10
        PaddingRight: =10
        PaddingTop: =20
        Visible: =vsbBtn
        Width: =170
        X: =606
        Y: =280
        ZIndex: =12

    cms_btn_tasaCambio_3 As button:
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(0, 0, 0, 0)
        DisabledFill: =RGBA(0, 0, 0, 0)
        Fill: =Color.Transparent
        Height: =140
        HoverFill: =Color.Transparent
        PressedFill: =Color.Transparent
        Text: =""
        Visible: =vsbBtn
        Width: =170
        X: =606
        Y: =280
        ZIndex: =13

    cms_lbl_tasaCambio_3 As label:
        Align: =Align.Center
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        Fill: =RGBA(255, 255, 255, 1)
        Font: =Font.Lato
        FontWeight: =FontWeight.Semibold
        Height: =36
        Text: ="Tasa de Cambio"
        Visible: =vsbBtn
        Width: =170
        X: =606
        Y: =420
        ZIndex: =14

    cms_img_productos_11 As image:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        Fill: =RGBA(255, 255, 255, 1)
        Height: =140
        Image: =catalogos2
        PaddingBottom: =20
        PaddingLeft: =10
        PaddingRight: =10
        PaddingTop: =20
        Visible: =vsbBtn
        Width: =170
        X: =1048
        Y: =280
        ZIndex: =15

    cms_btn_productos_9 As button:
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(0, 0, 0, 0)
        DisabledFill: =RGBA(0, 0, 0, 0)
        Fill: =Color.Transparent
        Height: =140
        HoverFill: =Color.Transparent
        PressedFill: =Color.Transparent
        Text: =""
        Visible: =vsbBtn
        Width: =170
        X: =1048
        Y: =280
        ZIndex: =16

    cms_lbl_productos_9 As label:
        Align: =Align.Center
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        Fill: =RGBA(255, 255, 255, 1)
        Font: =Font.Lato
        FontWeight: =FontWeight.Semibold
        Height: =36
        Size: =12
        Text: ="Otras Configuraciones"
        Visible: =vsbBtn
        Width: =170
        X: =1048
        Y: =420
        ZIndex: =17

    ps_img_backP_9 As image:
        Height: =47
        Image: =back
        PaddingBottom: =3
        PaddingTop: =3
        Width: =58
        X: =46
        Y: =715
        ZIndex: =21

    ps_btn_backP_9 As button:
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(0, 0, 0, 0)
        DisabledFill: =RGBA(0, 0, 0, 0)
        Fill: =Color.Transparent
        Height: =47
        HoverFill: =Color.Transparent
        OnSelect: =Back();
        PressedFill: =Color.Transparent
        Text: =""
        Width: =58
        X: =46
        Y: =715
        ZIndex: =22

